services:
  ping-police:
    image: ghcr.io/ingoau/ping-police:main
    restart: unless-stopped
    environment:
      SLACK_TOKEN: ${SLACK_TOKEN:?required}
      SLACK_APP_TOKEN: ${SLACK_APP_TOKEN:?required}
      SLACK_SELFBOT_XOXC: ${SLACK_SELFBOT_XOXC:?required}
      SLACK_SELFBOT_XOXD: ${SLACK_SELFBOT_XOXD:?required}
      PING_POLICE_USER_ID: ${PING_POLICE_USER_ID:?required}
      SELF_BOT_USER_ID: ${SELF_BOT_USER_ID:?required}
      REPORT_USER_ID: ${REPORT_USER_ID:-U0923H02Y3B}
      SQLITE_PATH: /data/sqlite.db
    volumes:
      - ping-police-data:/data

volumes:
  ping-police-data:
